### ISSUE TITLE
Request new tag due to issue with keras2json.py in v2.9

### ISSUE THREAD

**Issue by karavdin** [lwtnn/lwtnn#98]
Hi,
I'm going to use this tool as part of external packages in our framework and thus must stick to version with tags. In the most up date v2.9 there is some issue with keras2json.py, it fails with:
lwtnn converter being configured for keras (v2.2).
Traceback (most recent call last):
  File "/nfs/dust/cms/user/karavdia/lwtnn/converters/keras2json.py", line 159, in <module>
    _run()
  File "/nfs/dust/cms/user/karavdia/lwtnn/converters/keras2json.py", line 59, in _run
    'layers': _get_layers(arch, inputs, h5),
  File "/nfs/dust/cms/user/karavdia/lwtnn/converters/keras2json.py", line 125, in _get_layers
    layer_arch = in_layers[layer_n]
KeyError: 0

This seems to be fixed in current master branch some time ago (https://github.com/lwtnn/lwtnn/commit/35c6b52155adfc77fba667211767cd206d14425d). 
Is it possible to create new tag with fixed script, please?

**Comment by dguest** [comment]
This should be solved in v2.10.
